ALTER TABLE lore_sidebar_groups
ADD COLUMN IF NOT EXISTS category_id INTEGER;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'lore_sidebar_groups'
          AND column_name = 'axis_id'
    ) AND EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'lore_sidebar_groups'
          AND column_name = 'match_value'
    ) THEN
        UPDATE lore_sidebar_groups AS sidebar_group
        SET category_id = category_value.id
        FROM categories AS category_value
        WHERE category_value.axis_id = sidebar_group.axis_id
          AND category_value.name = sidebar_group.match_value
          AND sidebar_group.category_id IS NULL;

        IF EXISTS (
            SELECT 1
            FROM lore_sidebar_groups
            WHERE category_id IS NULL
        ) THEN
            RAISE EXCEPTION 'Unable to backfill lore_sidebar_groups.category_id for all rows';
        END IF;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.table_constraints
        WHERE table_schema = 'public'
          AND table_name = 'lore_sidebar_groups'
          AND constraint_name = 'lore_sidebar_groups_category_id_fkey'
    ) THEN
        ALTER TABLE lore_sidebar_groups
        ADD CONSTRAINT lore_sidebar_groups_category_id_fkey
        FOREIGN KEY (category_id)
        REFERENCES categories(id);
    END IF;
END $$;

ALTER TABLE lore_sidebar_groups
ALTER COLUMN category_id SET NOT NULL;

CREATE INDEX IF NOT EXISTS lore_sidebar_groups_lore_id_display_order_idx
ON lore_sidebar_groups (lore_id, display_order);

ALTER TABLE lore_sidebar_groups
DROP CONSTRAINT IF EXISTS lore_sidebar_groups_axis_id_fkey;

ALTER TABLE lore_sidebar_groups
DROP COLUMN IF EXISTS axis_id;

ALTER TABLE lore_sidebar_groups
DROP COLUMN IF EXISTS match_value;

CREATE TABLE IF NOT EXISTS lore_entity_modal_badge_rules (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lore_id INTEGER NOT NULL REFERENCES lores(id) ON DELETE CASCADE,
    category_id INTEGER NOT NULL REFERENCES categories(id),
    label VARCHAR(255) NOT NULL,
    display_order INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS lore_entity_modal_badge_rules_lore_id_display_order_idx
ON lore_entity_modal_badge_rules (lore_id, display_order, id);

CREATE TABLE IF NOT EXISTS lore_entity_modal_tag_axes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lore_id INTEGER NOT NULL REFERENCES lores(id) ON DELETE CASCADE,
    axis_id INTEGER NOT NULL REFERENCES category_axes(id),
    display_order INTEGER NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS lore_entity_modal_tag_axes_lore_id_axis_id_key
ON lore_entity_modal_tag_axes (lore_id, axis_id);

CREATE INDEX IF NOT EXISTS lore_entity_modal_tag_axes_lore_id_display_order_idx
ON lore_entity_modal_tag_axes (lore_id, display_order, id);
